### ISSUE TITLE
Inaccessible cache file uploads empty file to server

### ISSUE THREAD

**Issue by therarecommoner** [morassman/atom-commander#19] opened 2016-01-16 21:27 UTC
I admit two things: 1) that's a hard subject line to parse 2) I'm not sure how to best communicate the failure mode I've encountered. But I'll try and hope that you can let me know what to do when I encounter again - has happened several times - to help you diagnose.

I'm connected to a server
I have several php files from the server open
I make a change to one, view the site and get a missing functions error, such that the site doesn't load only the error
I review all the php files. All functions are correct and intact
I attempt a save against them after inconsequential changes
*here is where the issue surfaces in the atom UI*

I notice on one file - not always the same, has been php and CSS at varying instances - does not render the green pop up confirming a successful save, no matter how many attempts.

*the file on the server is empty

If I don't copy the full text, close the file and chose to NOT open from cache, I'll lose all work as it pulls the empty file from the server.

If I DO choose to open from cache, nothing happens. The file doesn't open and its as if I did not enter the command.

This just happened to me and I forgot to copy the text and lost my entire functions.php file for a WordPress site I'm developing. 

How can I help to kill this bug?

**Comment by therarecommoner** [comment] 2016-01-16 22:03
Happened again: Noticed when I hit save and immediately hit cmd-tab to switch apps to view the change, that the save action confirmation didn't appear, I was then no longer able to save the file on arbitrary changes, saw the undefined function error on the site, and upon returning and closing the file, got the prompt to open from cache or from the server - in this instance, neither action has any outcome, the app ignores the command as if I hadn't made it. 

If past incidents hold, I'll need to refresh atom (e.g., closing/opening atom commander) connect to the server again, open the empty file, then copy the previously lost content into before successfully being able to save. 

I'll play about a bit more to see if this replication pattern holds.

**Comment by morassman** [comment] 2016-01-16 22:45
This is pretty bad. The fact that the green pop-up doesn't appear may mean that it is silently failing in the background. Even if it does fail, however, I find it unsettling that the file on the server ends up empty.

Third party libraries are used for FTP and SFTP support. It may be that there is a bug there. It may even be that the FTP server being communicated with has an issue, although that is rather unlikely.

I'll try to reproduce and debug this as much as I can, but I may end up needing your help if I don't make progress. I may have to create my own WordPress account to test with...

In the mean time, maybe use one of the other FTP packages such as [remote-ftp](https://atom.io/packages/remote-ftp) or [remote-edit](https://atom.io/packages/remote-edit). These packages use the same third party libraries for FTP that Atom Commander does, so it may not help, but it's worth a try.

For now it will help to know: Are you using FTP or SFTP?

**Comment by therarecommoner** [comment] 2016-01-16 23:35
Hello @morassman thnks for getting back. I'm using FTP. 

I've actually used both of those but found atom commander to be superior particularly in connection persistence, config creation, and the directory location bar which allows me to hop about without navigating the folder structure, and no project requirement - so kudos there.

However, I'll give remote-ftp another go, though it may mean less opp for me to communicate replication states. Thing is, as long as I'm being mindful, I can catch it BEFORE closing the affected file and selecting to use the server version - thereby removing the cache (which is typically not available anyhow) and ultimately wiping my source. The issue expresses itself very particularly and consistently. Anyhow, I appreciate your tool and am willing to help in whichever way you think helpful as mentioned before. So let me know and it'll be done. 

Best,

**Comment by morassman** [comment] 2016-01-18 18:24
Cool. Thanks!

I develop and test on OSX and also test with the FTP server that comes with it, so my environment might be different from yours. I tried to reproduce the issue by opening multiple files over an FTP connection and making many changes and saving them over and over, but everything worked fine.

The best would be if I could test and debug with an environment that's as close as possible to yours. For that I'll need to know:
1.) What OS you are running Atom in.
2.) More details about the FTP server:
2.1.) Are you hosting the server?
2.2.) Do you know what OS it's running on?
2.3.) Do you know what software is used for the FTP server? FileZilla maybe?

Another option, but this is totally up to you, is to create a test folder on the server and give me access to it. Maybe you can set up the security in such a way that I can access only that folder. This is just a suggestion so don't worry if you don't like the idea :)

Also. What are your Atom Commander settings? From your comments a gather that "Upload On Save" is enabled. What about "Remove On Close"?

**On another note**
I read your first comment again and something caught my attention. You said "If I DO choose to open from cache, nothing happens. The file doesn't open and its as if I did not enter the command."

What Atom Commander does in the background is the following:
- It creates a hidden ".atom-commander" folder in your home folder.
- Inside that folder it creates a folder called "servers", which in turn contains a folder for each of the servers.
- The name of the server's folder is a combination of the protocol, URL, port number and username.
- Inside that folder is one called "cache", which forms the root of the cache for that server.

When you save the file then the one in the cache is simply copied to the server. If the file on the server ends up empty then there's the possibility that the file in the cache is empty as well. On the other hand,  the fact that you can't open the file from the cache may mean that the file doesn't exist anymore.

Maybe the path that is constructed is an invalid file path on your OS? You can see the full path by hovering the cursor over the tab of the opened file in Atom.

Try the following:
- Open a file over FTP.
- Hover over the tab to see where on the file system it is.
- Navigate there with a file manager (You can even use Atom Commander for that)
- See if the file is there.
- If it is, check to see if it is empty.
- If everything is OK, then keep an eye on that file and try to reproduce the issue. It may be that at some point it ends up empty or deleted. If that's the case then the bug is local and not on the server.

**Comment by therarecommoner** [comment] 2016-01-25 03:37
Hey apologies - just wanted to confirm I'm still here, but will need to digest the update you posted and gather the responses. Gimme a bit.

**Comment by morassman** [comment] 2016-01-25 07:04
Don't worry. There's no rush. Let me know if you have any questions or suggestions.

**Comment by morassman** [comment] 2016-09-24 17:58
Just checking up on this. There's been a few updates to Atom Commander since this bug was logged. I haven't been able to reproduce it. Does it still occur? If it doesn't or if you're using another package instead then I'd like to close this issue.

**Closed** 2016-10-09 18:27 UTC
