### ISSUE TITLE
Renaming a remote file deletes the file

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#35] opened 2016-08-25 03:13 UTC
When I select a remote file and then select F2 and enter a new name for it, the file disappears!

**Comment by morassman** [comment] 2016-08-25 16:32
I haven't been able to reproduce this, so I'll need a bit more info from you.

1.) Are you using FTP or SFTP?

2.) Does the file just disappear from Atom Commander's view or does it get deleted from the server's file system?

**Comment by toonbon** [comment] 2016-08-25 17:49
1. I'm using SFTP. 

2. The file is actually  deleted from the server's file system. 

Let me know any other way I can help you.

**Comment by morassman** [comment] 2016-08-25 18:56
Ok. That's pretty bad. I use [ssh2](https://www.npmjs.com/package/ssh2) for SFTP. Atom Commander simply makes use of its rename API, so it may be a bug with the library. I'll look into it.

**Comment by toonbon** [comment] 2016-08-25 19:25
I just tried setting up an FTP connection, using AC and also notepad++,  but it appears that the server at WP Engine, where my files are, won't accept an FTP connection.

**Comment by morassman** [comment] 2016-09-17 15:47
This was also due to the local path separator being used. Fixed in v0.7.2

**Closed by morassman** 2016-09-17 15:47 UTC
