### ISSUE TITLE
Clicking on a folder "expands" the tree view

### ISSUE THREAD

**Issue by WillyKirsch** [morassman/atom-commander#24] opened 2016-02-28 00:59 UTC
Hi, I was using the plug in with no issues until a few days ago that the treeview started to expand/jump up to half of the screen when you click on a folder or right click to use the contextual menu...

how I can solve it?
Thank you!

**Comment by morassman** [comment] 2016-02-28 08:59
This may be related to [another](https://github.com/thomaslindstrom/color-picker/issues/143) issue that was reported when the [color-picker](https://atom.io/packages/color-picker) package is installed.

Do you perhaps have color-picker installed? Please also attach a screenshot of what it looks like. I haven't been able to reproduce this though. Are there any reproduction steps I can follow that consistently causes this to happen?

**Comment by WillyKirsch** [comment] 2016-02-28 16:57
Actually yes! I installed the coli picker package!

I'm not at my desk now, but when I get there I'll post an screenshot and
additional information.

Thank you!

**Comment by WillyKirsch** [comment] 2016-02-28 21:36
Hi, I checked, and the las pkg that I installed, was minimap and previously color picker, but the problem started with color picker.

follows an normal screen first

![normal](https://cloud.githubusercontent.com/assets/9601026/13382026/853dcf72-de49-11e5-862f-cbea7bd7bed1.png)

then if you make just one click with left or right button:

![click on mydocuments](https://cloud.githubusercontent.com/assets/9601026/13382039/b58d9fea-de49-11e5-88a1-3c1a3b6a76a2.png)

TADAAA!!

the screen jumps up!!.

on the next click nothing happens, then you click again, and the screens returns to it's original layout.

Best Regards!

**Comment by WillyKirsch** [comment] 2016-02-28 21:38
I just uninstalled the color picker, and the problem go off!!.

Best Regards

**Comment by morassman** [comment] 2016-02-29 07:11
Thanks. I'll open the issue again on color-picker. In the mean time you can try the following: The last time this issue was reported it was found that, if the color picker is shown at least once then the empty space doesn't appear. Give it a try when you install color-picker again. Before clicking on Atom Commander, just open the color picker window once and close it again. Clicking on Atom Commander then shouldn't cause the empty space to appear.

**Comment by WillyKirsch** [comment] 2016-02-29 12:30
Thank you! I will try it and report the results.
Best regards!

**Comment by WillyKirsch** [comment] 2016-02-29 19:47
Hi, I've tried and worked, so that is a workaround until the color picker
problem is finally solved.
Thank you!

**Comment by morassman** [comment] 2016-02-29 20:01
Great! I'm glad the workaround still works. Hopefully it won't be needed for much longer.

**Comment by WillyKirsch** [comment] 2016-02-29 21:56
Yeah I'm Sure, thank you!!

2016-02-29 17:01 GMT-03:00 morassman <notifications@github.com>:

> Great! I'm glad the workaround still works. Hopefully it won't be needed
> for much longer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/morassman/atom-commander/issues/24#issuecomment-190358095>
> .
>



-- 
Salu2

**Comment by morassman** [comment] 2016-08-27 13:59
This issue only appears when color picker is installed and may be due to a bug on its side. It may also have been fixed in the mean time.

**Closed by morassman** 2016-08-27 13:59 UTC
