### ISSUE TITLE
Uncaught InvalidAsn1Error: Expected 0x2: got 0x9c

### ISSUE THREAD

**Issue by deem0n** [morassman/atom-commander#55] opened 2016-12-14 09:34 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package, v0.8.4

### Stack Trace

Uncaught InvalidAsn1Error: Expected 0x2: got 0x9c

```
At /Users/deem0n/.atom/packages/atom-commander/node_modules/asn1/lib/ber/reader.js:229

InvalidAsn1Error: Expected 0x2: got 0x9c
    at newInvalidAsn1Error (/Users/deem0n/.atom/packages/atom-commander/node_modules/asn1/lib/ber/errors.js:7:13)
    at Reader._readTag (/Users/deem0n/.atom/packages/atom-commander/node_modules/asn1/lib/ber/reader.js:229:11)
    at Reader.readInt (/Users/deem0n/.atom/packages/atom-commander/node_modules/asn1/lib/ber/reader.js:145:15)
    at genPublicKey (/Users/deem0n/.atom/packages/atom-commander/node_modules/ssh2-streams/lib/utils.js:437:19)
    at Client.connect (/Users/deem0n/.atom/packages/atom-commander/node_modules/ssh2/lib/client.js:234:29)
    at SFTPDialog.module.exports.SFTPDialog.test (/Users/deem0n/.atom/packages/atom-commander/lib/dialogs/sftp-dialog.coffee:367:11)
    at HTMLButtonElement.<anonymous> (/Users/deem0n/.atom/packages/atom-commander/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/Users/deem0n/.atom/packages/atom-commander/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Users/deem0n/.atom/packages/atom-commander/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:23.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:01.9.0 atom-commander:toggle-focus (div.package-detail.panels-item)
 18x -3:44.5.0 core:move-down (atom-text-editor.editor.mini.directory-editor.is-focused)
     -3:42.3.0 core:move-up (atom-text-editor.editor.mini.directory-editor.is-focused)
  2x -3:42.1.0 core:move-down (atom-text-editor.editor.mini.directory-editor.is-focused)
 22x -3:41.6.0 core:move-up (atom-text-editor.editor.mini.directory-editor.is-focused)
     -3:36.6.0 atom-commander:toggle-visible (atom-text-editor.editor.mini.directory-editor.is-focused)
     -3:23 atom-commander:toggle-focus (atom-text-editor.editor.is-focused)
     -3:03.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -3:03.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:53.4.0 atom-commander:add-server (td..directory.icon.icon-file-directory)
  3x -1:34 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:11 atom-commander:add-server (td..directory.icon.icon-file-directory)
  2x -0:51.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
  6x -0:06.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:05.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.40 (active)
atom-beautify, v0.29.13 (active)
atom-commander, v0.8.4 (active)
dash, v1.7.0 (inactive)
git-plus, v5.29.0 (active)
language-elm, v1.5.0 (active)
language-haskell, v1.10.1 (active)
language-lua, v0.9.11 (active)
language-pgsql, v0.2.3 (active)
language-scheme, v1.4.0 (active)
linter, v1.11.18 (active)
quantum-shell, v0.7.1 (inactive)
quick-query, v0.8.8 (inactive)
regex-railroad-diagram, v0.16.0 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by deem0n** [comment] 2016-12-14 09:40
Can not use private key to connect over sftp :-(

**Comment by morassman** [comment] 2016-12-17 13:31
I wasn't able to reproduce this behaviour exactly, but I did have trouble connect to an SFTP server. I've released version 0.8.5 that uses the latest SFTP library. Upgrading the library solved the problem I was having. See if updating to 0.8.5 will work for you as well.

**Comment by deem0n** [comment] 2016-12-20 10:27
Thank you, but nope:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package, v0.8.5


### Stack Trace

Uncaught InvalidAsn1Error: Expected 0x2: got 0xb8

```
At /Users/deem0n/.atom/packages/atom-commander/node_modules/asn1/lib/ber/reader.js:229

InvalidAsn1Error: Expected 0x2: got 0xb8
    at newInvalidAsn1Error (/Users/deem0n/.atom/packages/atom-commander/node_modules/asn1/lib/ber/errors.js:7:13)
    at Reader._readTag (/Users/deem0n/.atom/packages/atom-commander/node_modules/asn1/lib/ber/reader.js:229:11)
    at Reader.readInt (/Users/deem0n/.atom/packages/atom-commander/node_modules/asn1/lib/ber/reader.js:145:15)
    at genPublicKey (/Users/deem0n/.atom/packages/atom-commander/node_modules/ssh2-streams/lib/utils.js:437:19)
    at Client.connect (/Users/deem0n/.atom/packages/atom-commander/node_modules/ssh2/lib/client.js:234:29)
    at SFTPDialog.module.exports.SFTPDialog.test (/Users/deem0n/.atom/packages/atom-commander/lib/dialogs/sftp-dialog.coffee:367:11)
    at HTMLButtonElement.<anonymous> (/Users/deem0n/.atom/packages/atom-commander/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/Users/deem0n/.atom/packages/atom-commander/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Users/deem0n/.atom/packages/atom-commander/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:28.1.0 atom-commander:remove-server (td..directory.icon.icon-arrow-up)
     -0:15.6.0 atom-commander:add-server (td..directory.icon.icon-arrow-up)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.40 (active)
atom-beautify, v0.29.14 (inactive)
atom-commander, v0.8.5 (active)
dash, v1.7.0 (inactive)
git-plus, v5.29.1 (active)
language-elm, v1.5.0 (active)
language-haskell, v1.10.1 (active)
language-lua, v0.9.11 (active)
language-pgsql, v0.2.3 (active)
language-scheme, v1.4.0 (active)
linter, v1.11.18 (active)
quantum-shell, v0.7.1 (inactive)
quick-query, v0.8.8 (inactive)
regex-railroad-diagram, v0.16.0 (active)
SFTP-deployment, v1.0.2 (inactive)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by deem0n** [comment] 2016-12-20 10:31
But I can confirm, that I can connect using password.

**Comment by morassman** [comment] 2016-12-20 11:10
Thanks. That's good to know. At least we know that you can actually connect to the server.

The error occurs in the ssh2-streams library. I checked the code and it happens when it tries to parse the version of the key. It expects to read an integer at a particular location, but finds something else instead.

Atom Commander simply takes the key and passes it on to ssh2-streams. I think it's unlikely for ssh2-streams to have a bug  in such a place though, because its already used by many other libraries. It may be that there's something not quite right with your key. From the code I can see that it should be either RSA, DSA or ECDSA.

**Comment by deem0n** [comment] 2016-12-20 11:56
I use
```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,47B1E60FBAFB124762595388ADC34829
```

**Comment by morassman** [comment] 2016-12-20 12:37
I see. Mine doesn't have the Proc-Type and DEK-Info at the top. I assume you are using a passphrase along with the private key?

On [this](http://phpseclib.sourceforge.net/rsa/examples.html) site you can see the difference. If you choose the private key format as `PKCS#1` then you get the one and when you choose `PKCS#1 (with password)` you get the one you have.

Can you confirm whether you are indeed using a passphrase? If that is the case then it might help me debug this better.

**Comment by morassman** [comment] 2016-12-20 20:32
I was able to reproduce the issue by generating a key with a passphrase. The only time I get the same error as you is when the passphrase was entered incorrectly.

I also saw another thing. It looks like you have to specify both the password and the passphrase. This can be a bit misleading due to how the settings require that either of the two should be entered. I was therefore able to connect with a passphrase encrypted key by specifying both the password and the passphrase. If these two are different then make sure you enter the right one in the right place.

Let me know if this works. I'll also make the UI and documentation more clear.

**Comment by deem0n** [comment] 2016-12-21 10:14
Ah, surely my keys are protected with passphrase and I completely forgot that!

If I check 'Use passphrase' and type it in, then everything works as expected.

It would be nice if we can have better error message. Thank you for support and pretty commander. It is really handy tool.

**Comment by morassman** [comment] 2016-12-21 10:24
You're welcome!

That's how I expected it to work. It doesn't make sense to me that mine only works when I provide both the password and the passphrase, but that sounds like a different issue that I'll have to look into.

I'm glad to hear that it's working now. During my debugging I've also started improving the error handling, so that will be part of the next update.

**Closed by morassman** 2016-12-21 10:24 UTC
